import Head from 'next/head'
import { createComponent } from '@lit-labs/react'
import { IxVideo } from '@imgix/ix-video'
import styles from '../styles/Home.module.css'
import TheHeader from '../components/TheHeader'
import TheFooter from '../components/TheFooter'

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Video
          controls
          source="https://assets.imgix.video/videos/girl-reading-book-in-library.mp4"
          onSeeked={(e) => console.log(e)}
        />
        <TheHeader />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <h2
            id="collections-heading"
            className="text-2xl text-center font-extrabold text-white"
          >
            Testing HLS (Left) vs MP4 (Right)
          </h2>
          <h3
            id="collections-heading"
            className="text-lg text-center font-extrabold text-white"
          >
            Try Throttling Your Network Tab to 3G to See HLS Adapt to Lower
            Quality Networks. Press play on both videos.
          </h3>
        </div>
      </div>
      <TheFooter />
    </>
  )
}

export const Video = createComponent(React, 'ix-video', IxVideo, {
  onSeeked: 'seeked',
})
